// GENERATED by tools/build_problems.mjs. Do not edit by hand.
// Source: data/problem_bank_v1.json (answers verified with exact arithmetic) + tools/annotations.mjs

export const PROBLEMS = [
  {
    "id": "r01",
    "skill": "S1",
    "context": "class",
    "question": "A class has 12 girls and 16 boys. What is the ratio of girls to boys, in simplest form?",
    "answer_type": "ratio",
    "answer": [
      3,
      4
    ],
    "known_wrong": [
      {
        "value": [
          4,
          3
        ],
        "tag": "M2"
      },
      {
        "value": [
          3,
          7
        ],
        "tag": "M3"
      },
      {
        "value": [
          12,
          28
        ],
        "tag": "M3"
      }
    ],
    "simplest": true,
    "example": "r03",
    "display": "3 : 4",
    "unit": null,
    "steps": [
      "The question asks for girls to boys, so the number of girls comes first.",
      "Girls to boys is 12 : 16. Both numbers can be divided by 4: 12 ÷ 4 = 3 and 16 ÷ 4 = 4.",
      "In simplest form, the ratio of girls to boys is 3 : 4."
    ]
  },
  {
    "id": "r02",
    "skill": "S1",
    "context": "fruit",
    "question": "A fruit bowl has 5 apples and 3 oranges. What fraction of all the fruit is apples?",
    "answer_type": "fraction",
    "answer": [
      5,
      8
    ],
    "known_wrong": [
      {
        "value": [
          5,
          3
        ],
        "tag": "M3"
      },
      {
        "value": [
          3,
          8
        ],
        "tag": "M3"
      }
    ],
    "example": "r01",
    "display": "5/8",
    "unit": null,
    "steps": [
      "First find all the fruit: 5 + 3 = 8 pieces.",
      "Apples are 5 of those 8 pieces.",
      "So apples are 5/8 of all the fruit."
    ]
  },
  {
    "id": "r03",
    "skill": "S1",
    "context": "smoothie",
    "question": "A smoothie uses 2 cups of strawberries for every 3 cups of yogurt. What is the ratio of yogurt to strawberries?",
    "answer_type": "ratio",
    "answer": [
      3,
      2
    ],
    "known_wrong": [
      {
        "value": [
          2,
          3
        ],
        "tag": "M2"
      },
      {
        "value": [
          3,
          5
        ],
        "tag": "M3"
      }
    ],
    "simplest": true,
    "example": "r01",
    "display": "3 : 2",
    "unit": null,
    "steps": [
      "The question asks for yogurt first, then strawberries.",
      "There are 3 cups of yogurt for every 2 cups of strawberries.",
      "So the ratio of yogurt to strawberries is 3 : 2."
    ]
  },
  {
    "id": "r04",
    "skill": "S1",
    "context": "sports",
    "question": "A soccer team won 18 games and lost 6. What is the ratio of wins to total games played, in simplest form?",
    "answer_type": "ratio",
    "answer": [
      3,
      4
    ],
    "known_wrong": [
      {
        "value": [
          3,
          1
        ],
        "tag": "M3"
      },
      {
        "value": [
          1,
          4
        ],
        "tag": "M3"
      },
      {
        "value": [
          4,
          3
        ],
        "tag": "M2"
      }
    ],
    "simplest": true,
    "example": "r02",
    "display": "3 : 4",
    "unit": null,
    "steps": [
      "Total games played: 18 + 6 = 24.",
      "Wins to total games is 18 : 24.",
      "Divide both by 6: 18 ÷ 6 = 3 and 24 ÷ 6 = 4, so the ratio is 3 : 4."
    ]
  },
  {
    "id": "r05",
    "skill": "S2",
    "context": "baking",
    "question": "A cookie recipe uses 3 cups of flour for every 2 cups of sugar. How many cups of flour go with 8 cups of sugar?",
    "answer_type": "number",
    "answer": 12,
    "known_wrong": [
      {
        "value": 9,
        "tag": "M1"
      },
      {
        "value": {
          "num": 16,
          "den": 3
        },
        "tag": "M4"
      }
    ],
    "example": "r06",
    "display": "12 cups of flour",
    "unit": "cups",
    "steps": [
      "Sugar goes from 2 cups to 8 cups: 8 ÷ 2 = 4, so the recipe is 4 times as big.",
      "Flour has to grow by the same factor: 3 × 4 = 12.",
      "So 12 cups of flour go with 8 cups of sugar."
    ]
  },
  {
    "id": "r06",
    "skill": "S2",
    "context": "art",
    "question": "A paint mix uses 4 cups of blue for every 6 cups of yellow. How many cups of yellow go with 10 cups of blue?",
    "answer_type": "number",
    "answer": 15,
    "known_wrong": [
      {
        "value": 12,
        "tag": "M1"
      },
      {
        "value": {
          "num": 20,
          "den": 3
        },
        "tag": "M4"
      }
    ],
    "example": "r08",
    "display": "15 cups of yellow",
    "unit": "cups",
    "steps": [
      "Blue goes from 4 cups to 10 cups: 10 ÷ 4 = 2.5, so the mix is 2.5 times as big.",
      "Yellow has to grow by the same factor: 6 × 2.5 = 15.",
      "So 15 cups of yellow go with 10 cups of blue."
    ]
  },
  {
    "id": "r07",
    "skill": "S2",
    "context": "running",
    "question": "Jada runs 5 laps every 2 minutes. At the same pace, how many minutes does it take her to run 15 laps?",
    "answer_type": "number",
    "answer": 6,
    "known_wrong": [
      {
        "value": 12,
        "tag": "M1"
      },
      {
        "value": {
          "num": 75,
          "den": 2
        },
        "tag": "M4"
      }
    ],
    "example": "r05",
    "display": "6 minutes",
    "unit": "minutes",
    "steps": [
      "Laps go from 5 to 15: 15 ÷ 5 = 3, so she runs 3 times as many laps.",
      "Time grows by the same factor: 2 × 3 = 6.",
      "So it takes Jada 6 minutes to run 15 laps."
    ]
  },
  {
    "id": "r08",
    "skill": "S2",
    "context": "ratio table",
    "question": "Fill in the missing number so the ratios are equivalent: 6 : 9 = 12 : ?",
    "answer_type": "number",
    "answer": 18,
    "known_wrong": [
      {
        "value": 15,
        "tag": "M1"
      },
      {
        "value": 8,
        "tag": "M4"
      }
    ],
    "example": "r05",
    "display": "18",
    "unit": null,
    "steps": [
      "The first numbers go from 6 to 12: 12 ÷ 6 = 2, so the ratio is doubled.",
      "The second number has to double too: 9 × 2 = 18.",
      "So 6 : 9 = 12 : 18."
    ]
  },
  {
    "id": "r09",
    "skill": "S3",
    "context": "travel",
    "question": "A car travels 150 miles in 3 hours at a steady speed. How many miles does it travel per hour?",
    "answer_type": "number",
    "answer": 50,
    "known_wrong": [
      {
        "value": {
          "num": 1,
          "den": 50
        },
        "tag": "M4"
      },
      {
        "value": 450,
        "tag": "M4"
      }
    ],
    "example": "r11",
    "display": "50 miles per hour",
    "unit": "miles",
    "steps": [
      "Per hour means: how many miles for 1 hour?",
      "Split the miles evenly over the hours: 150 ÷ 3 = 50.",
      "So the car travels 50 miles per hour."
    ]
  },
  {
    "id": "r10",
    "skill": "S3",
    "context": "shopping",
    "question": "A pack of 12 pencils costs $3. How much does one pencil cost, in dollars?",
    "answer_type": "number",
    "answer": {
      "num": 1,
      "den": 4
    },
    "known_wrong": [
      {
        "value": 4,
        "tag": "M4"
      },
      {
        "value": 36,
        "tag": "M4"
      }
    ],
    "example": "r09",
    "display": "$0.25",
    "unit": "dollars",
    "steps": [
      "One pencil means: how many dollars for 1 pencil?",
      "Split the cost evenly over the pencils: 3 ÷ 12 = 0.25.",
      "So one pencil costs $0.25."
    ]
  },
  {
    "id": "r11",
    "skill": "S3",
    "context": "reading",
    "question": "Maya reads 45 pages in 1.5 hours. How many pages does she read per hour?",
    "answer_type": "number",
    "answer": 30,
    "known_wrong": [
      {
        "value": {
          "num": 1,
          "den": 30
        },
        "tag": "M4"
      },
      {
        "value": {
          "num": 135,
          "den": 2
        },
        "tag": "M4"
      },
      {
        "value": {
          "num": 89,
          "den": 2
        },
        "tag": "M1"
      }
    ],
    "example": "r09",
    "display": "30 pages per hour",
    "unit": "pages",
    "steps": [
      "Per hour means: how many pages for 1 hour?",
      "Split the pages evenly over the hours: 45 ÷ 1.5 = 30.",
      "So Maya reads 30 pages per hour."
    ]
  },
  {
    "id": "r12",
    "skill": "S3",
    "context": "printing",
    "question": "A printer prints 84 pages in 7 minutes. At the same rate, how many pages does it print in 12 minutes?",
    "answer_type": "number",
    "answer": 144,
    "known_wrong": [
      {
        "value": 89,
        "tag": "M1"
      },
      {
        "value": 49,
        "tag": "M4"
      }
    ],
    "example": "r09",
    "display": "144 pages",
    "unit": "pages",
    "steps": [
      "First find the unit rate: 84 ÷ 7 = 12 pages per minute.",
      "Then use it for 12 minutes: 12 × 12 = 144.",
      "So the printer prints 144 pages in 12 minutes."
    ]
  },
  {
    "id": "r13",
    "skill": "S4",
    "context": "percent",
    "question": "What is 30% of 60?",
    "answer_type": "number",
    "answer": 18,
    "known_wrong": [
      {
        "value": 2,
        "tag": "M5"
      },
      {
        "value": 200,
        "tag": "M5"
      },
      {
        "value": 30,
        "tag": "M5"
      }
    ],
    "example": "r16",
    "display": "18",
    "unit": null,
    "steps": [
      "30% means 30 out of every 100, which is 0.3.",
      "Take that part of 60: 0.3 × 60 = 18.",
      "So 30% of 60 is 18."
    ]
  },
  {
    "id": "r14",
    "skill": "S4",
    "context": "survey",
    "question": "18 out of 24 students chose pizza for the class party. What percent of students chose pizza?",
    "answer_type": "number",
    "answer": 75,
    "known_wrong": [
      {
        "value": {
          "num": 400,
          "den": 3
        },
        "tag": "M5"
      },
      {
        "value": 18,
        "tag": "M5"
      }
    ],
    "example": "r13",
    "display": "75%",
    "unit": "percent",
    "steps": [
      "The whole is all 24 students, and the part is the 18 who chose pizza.",
      "Part divided by whole: 18 ÷ 24 = 0.75.",
      "Change it to a percent: 0.75 × 100 = 75, so 75% chose pizza."
    ]
  },
  {
    "id": "r15",
    "skill": "S4",
    "context": "sale",
    "question": "A $40 video game is 25% off. What is the sale price, in dollars?",
    "answer_type": "number",
    "answer": 30,
    "known_wrong": [
      {
        "value": 10,
        "tag": "partial"
      },
      {
        "value": 15,
        "tag": "M5"
      }
    ],
    "example": "r16",
    "display": "$30",
    "unit": "dollars",
    "steps": [
      "25% off means the discount is 25% of $40: 0.25 × 40 = 10.",
      "Take the discount away from the price: 40 − 10 = 30.",
      "So the sale price is $30."
    ]
  },
  {
    "id": "r16",
    "skill": "S4",
    "context": "percent",
    "question": "12 is 20% of what number?",
    "answer_type": "number",
    "answer": 60,
    "known_wrong": [
      {
        "value": {
          "num": 12,
          "den": 5
        },
        "tag": "M5"
      },
      {
        "value": {
          "num": 5,
          "den": 3
        },
        "tag": "M5"
      }
    ],
    "example": "r14",
    "display": "60",
    "unit": null,
    "steps": [
      "20% means 20 out of 100, which is 0.2. So 12 is 0.2 of the whole.",
      "To find the whole, divide: 12 ÷ 0.2 = 60.",
      "So 12 is 20% of 60."
    ]
  },
  {
    "id": "r17",
    "skill": "S5",
    "context": "shopping",
    "question": "4 notebooks cost $10. At the same price each, how much do 10 notebooks cost, in dollars?",
    "answer_type": "number",
    "answer": 25,
    "known_wrong": [
      {
        "value": 16,
        "tag": "M1"
      },
      {
        "value": 4,
        "tag": "M4"
      }
    ],
    "example": "r19",
    "display": "$25",
    "unit": "dollars",
    "steps": [
      "Find the cost of 1 notebook: 10 ÷ 4 = 2.5 dollars.",
      "Then find the cost of 10 notebooks: 2.5 × 10 = 25.",
      "So 10 notebooks cost $25."
    ]
  },
  {
    "id": "r18",
    "skill": "S5",
    "context": "maps",
    "question": "On a map, 2 cm stands for 5 km. How many km does 7 cm stand for?",
    "answer_type": "number",
    "answer": {
      "num": 35,
      "den": 2
    },
    "known_wrong": [
      {
        "value": 10,
        "tag": "M1"
      },
      {
        "value": {
          "num": 14,
          "den": 5
        },
        "tag": "M4"
      }
    ],
    "example": "r17",
    "display": "17.5 km",
    "unit": "km",
    "steps": [
      "Find how many km 1 cm stands for: 5 ÷ 2 = 2.5 km.",
      "Then use it for 7 cm: 2.5 × 7 = 17.5.",
      "So 7 cm stands for 17.5 km."
    ]
  },
  {
    "id": "r19",
    "skill": "S5",
    "context": "algebra",
    "question": "y is proportional to x. When x = 3, y = 12. What is y when x = 5?",
    "answer_type": "number",
    "answer": 20,
    "known_wrong": [
      {
        "value": 14,
        "tag": "M1"
      },
      {
        "value": {
          "num": 5,
          "den": 4
        },
        "tag": "M4"
      }
    ],
    "example": "r18",
    "display": "20",
    "unit": null,
    "steps": [
      "Proportional means y is always the same number times x. Find that number: 12 ÷ 3 = 4.",
      "So y is always 4 times x. When x is 5: 4 × 5 = 20.",
      "So y = 20 when x = 5."
    ]
  },
  {
    "id": "r20",
    "skill": "S5",
    "context": "cooking",
    "question": "A soup recipe for 6 people uses 4 cups of broth. How many cups of broth are needed for 9 people?",
    "answer_type": "number",
    "answer": 6,
    "known_wrong": [
      {
        "value": 7,
        "tag": "M1"
      },
      {
        "value": {
          "num": 27,
          "den": 2
        },
        "tag": "M4"
      }
    ],
    "example": "r19",
    "display": "6 cups of broth",
    "unit": "cups",
    "steps": [
      "People go from 6 to 9: 9 ÷ 6 = 1.5, so the soup is 1.5 times as big.",
      "Broth grows by the same factor: 4 × 1.5 = 6.",
      "So 9 people need 6 cups of broth."
    ]
  }
];

export const SKILLS = [
  { id: "S1", name: "Ratio meaning", short: "Meaning", standard: "6.RP.A.1", prereqs: [] },
  { id: "S2", name: "Equivalent ratios", short: "Equivalent", standard: "6.RP.A.3a", prereqs: ["S1"] },
  { id: "S3", name: "Unit rates", short: "Rates", standard: "6.RP.A.2", prereqs: ["S2"] },
  { id: "S4", name: "Percent", short: "Percent", standard: "6.RP.A.3c", prereqs: ["S3"] },
  { id: "S5", name: "Proportions", short: "Proportions", standard: "7.RP.A.2", prereqs: ["S2"] },
];

export function getProblem(id) {
  return PROBLEMS.find((p) => p.id === id) || null;
}
