// Builds lib/problems.js from the verified bank (data/problem_bank_v1.json)
// plus the teaching annotations. Run: node tools/build_problems.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { ANNOTATIONS } from "./annotations.mjs";

const bank = JSON.parse(readFileSync(new URL("../data/problem_bank_v1.json", import.meta.url)));
const merged = bank.map((p) => {
  const a = ANNOTATIONS[p.id];
  if (!a) throw new Error(`Missing annotations for ${p.id}`);
  return { ...p, ...a };
});

const out = `// GENERATED by tools/build_problems.mjs. Do not edit by hand.
// Source: data/problem_bank_v1.json (answers verified with exact arithmetic) + tools/annotations.mjs

export const PROBLEMS = ${JSON.stringify(merged, null, 2)};

export const SKILLS = [
  { id: "S1", name: "Ratio meaning", short: "Meaning", standard: "6.RP.A.1", prereqs: [] },
  { id: "S2", name: "Equivalent ratios", short: "Equivalent", standard: "6.RP.A.3a", prereqs: ["S1"] },
  { id: "S3", name: "Unit rates", short: "Rates", standard: "6.RP.A.2", prereqs: ["S2"] },
  { id: "S4", name: "Percent", short: "Percent", standard: "6.RP.A.3c", prereqs: ["S3"] },
  { id: "S5", name: "Proportions", short: "Proportions", standard: "7.RP.A.2", prereqs: ["S2"] },
];

export function getProblem(id) {
  return PROBLEMS.find((p) => p.id === id) || null;
}
`;
writeFileSync(new URL("../lib/problems.js", import.meta.url), out);
console.log(`Wrote lib/problems.js with ${merged.length} problems`);
